spring:
  jpa:
    generate-ddl: true
  h2:
    console:
      enabled: true
bridge:
  server:
    datasource:
      serverDB:
        url: jdbc:h2:mem:serverDB
        username: sa
        password:
        driver-class-name: org.h2.Driver
